### ISSUE TITLE
Ruby Dev vacancy text missing some real technologies and concrete requirements

### ISSUE THREAD

**Issue by atatarenko** [datarockets/career#13]
From [the conversations](https://datarockets.slack.com/archives/C0H4KK3B7/p1614859431084800?thread_ts=1614851019.083500&cid=C0H4KK3B7) in chats:

> You can help with the last point by watching over the vacancy text and adding some real technologies and concrete requirements. There is no need to write it all down, I will be happy to do that, I just need to know key points (like specific names of technologies and requirements).

**Comment by atatarenko** [comment]
@maryiailiusina let me share the list of technologies for now and I'll come up with concrete requirements later. I mean, I'm pretty familiar with Glassfrog and its requirements, it's easier and harder at the same time, in comparison to writing requirements for some abstract senior vacancy. I'll share them when I got a solid picture myself but not just empty words (by Tuesday next week).

So here is the grouped list of techs (or you can just list them all without grouping):

- Ruby on Rails / GraphQL / PostgreSQL / ElasticSearch
- ES11 / React / React Relay / CSS Modules
- Flow Types / Webpack / Jest 
- Docker / Kubernetes / AWS

**Comment by atatarenko** [comment]
@an-korn @nixololo please review the list of techs ^. Add what seems reasonable to you.

**Comment by an-korn** [comment]
@atatarenko Maybe it makes sense to add also JavaScript in the list, not only React. This may imply knowledge of the language, but better to clarify, I guess. The same thing for Ruby on Rail. All the rest looks good to me.

**Comment by atatarenko** [comment]
Yeah, it makes sense. I put `ES11` since this means JavaScript (aka ECMAScript 2020 aka ES2020) but maybe this is not that obvious. @nixololo what's the best option in your thinking?

Re Ruby on Rails, I think putting Ruby there doesn't bring any extra value because this is a Ruby vacancy and Ruby on Rails includes Ruby word already so there are quite enough rubies in the vacancy text :)

**Comment by nixololo** [comment]
@atatarenko yeah, es11 totally uncommon and confusing. I'd say "ES6 and beyond" or just "modern javascript"

**Comment by nixololo** [comment]
BTW I'd like to separate things a bit. Some of them are really required (like ruby/rails/postgres) but other things can be learned during work on a project (like flow/react-relay/modern js features). It gonna be almost impossible to find a new folk in several months that will meet all our needs.

**Comment by atatarenko** [comment]
@nixololo got it

**Comment by atatarenko** [comment]
@nixololo I just listed the techs we use, not the requirements. Sometimes people join some project if they want to learn something (e.g. GraphQL/Relay) or they just want to make sure that we have test coverage (e.g. RSpec) or .... <- put your own option.

**Comment by atatarenko** [comment]
To be honest, in the case of a senior dev I don't care much about specific tools they've used. It totally doesn't make difference to me. If they are seniors they should be able to quickly learn things. If a candidate is more like "I'm not joining the project because Flow is an unknown tool and I can't learn" we don't need such a candidate.
