### ISSUE TITLE
Localization of vacancy text

### ISSUE THREAD

**Issue by atatarenko** [datarockets/career#15]
There is an interesting thing I noticed recently. As most of our hiring campaigns are focused on the CIS region why do we do that with vacancies written in English? I know that English is critical for our job but...for some reason, we promote English-written vacancies on Russian-localized websites.

How much it's efficient to promote the company in English for a primarily Russian-speaking audience?

**Comment by yuliagaranok** [comment]
The question is if we are comfortable with a level of English where people are comfortable only speak on technical terms? We have check-ins, we run half of the interviews in English to see if people can present themselves and speak with clients comfortably.

**Comment by atatarenko** [comment]
I understand that English is vital to our work, no doubts. Even taking that, being an average developer from the CIS region I never use English outside work – I never google how to treat stomachache in English, right?

We can check the speaking skills via a variety of approaches that are way better than checking an ability to read texts in English. I also hardly remember the case when we were like "this guy is a real engineer, awesome dev, cool tech skills but English is not that nice so we have to reject".

My point is **not about the importance of English** at work but mostly about **first engagement** to our vacancies so people who're looking for a job want to proceed with us not just to pass through.

**Comment by maryiailiusina** [comment]
@atatarenko I think it's a good point. As I see, what is important to us is a desire to master English skills rather than having a good level from the very beginning. So, it's okay for us to hire people with not good English.

When it comes to vacancies, I think it's obviously easier to catch more people to read in Russian, but at the same time, English text is also catchy for those who interested in international companies / remote work, because it's highlighted from the list of vacancies in Russian. 

Also, I remember Dima experimented with Russian and English texts and there was almost no difference. For me, I was striving to have all texts in English but didn't wonder how it would be better.

**Comment by atatarenko** [comment]
@maryiailiusina 

> I think it's a good point. As I see, what is important to us is a desire to master English skills rather than having a good level from the very beginning. So, it's okay for us to hire people with not good English.

Agree with you.

> When it comes to vacancies, I think it's obviously easier to catch more people to read in Russian, but at the same time, English text is also catchy for those who interested in international companies / remote work, because it's highlighted from the list of vacancies in Russian.

When I'm trying to think like average dev from the CIS, I guess that this an English-written vacancy might be catchy, right. Even if it's highlighted in comparison to other vacancies, this doesn't necessarily mean I'm gonna engage with that. At the same time, if I'm looking for an international company why would I do that on a Russian-speaking website. There is not enough glue from my perspective. 

> Also, I remember Dima experimented with Russian and English texts and there was almost no difference. For me, I was striving to have all texts in English but didn't wonder how it would be better.

Interesting point about the experiment. If there is no difference, it still feels like extra-work to promote the company among the Russian-speaking audience in English. I'm trying no to speculate but here is an example, I know that Coca-Cola is an international company, no doubt, but I've never seen their advertising in English being in Belarus.

**Comment by maryiailiusina** [comment]
@atatarenko I added this point to the next tactical.

Agree with your thoughts, indeed if there is no difference, it's an extra-work to write in English. With current vacancies - the texts are written already, so it's an extra-work to translate them to Russian. 

I'll let you know what we came up with after tactical and if needed, we can have a separate call/discussion for that.

**Comment by atatarenko** [comment]
> I added this point to the next tactical.

Great 👍 

I'm closing the issue...
